export type Attributes = {
  id: number;
  companyTitle: string;
  startAt: string;
  endAt: string;
  description: string;
  jobTitle: string;
  software_id: number;
  link: string;
  logo: string;
  title: string;
  name: string;
  username: string;
  surname: string;
  age: number;
  city: number;
  country: string;
  yearExperince: number;
  date: string;
  position: string;
};
